### DISCUSSION TITLE
Torch not compiled with CUDA enabled XPU (Intel GPU)

### DISCUSSION THREAD

**Discussion by slickygreasefat** [Acly/krita-ai-diffusion#2456] [General]
I am trying to get AI Diffusion working with XPU (Intel GPU) and it is giving me this error.
<img width="978" height="267" alt="image" src="https://github.com/user-attachments/assets/48ccca68-152c-4e57-ab3b-7c03bd251a7d" />

I really don't know why this has to be so complicated then it needs to be. I was wondering how I can fixed this issue because I been looking everywhere, but cant find anything.

[server.log](https://github.com/user-attachments/files/26847196/server.log)

**Comment by elmagio** [comment]
Hi, I'm having the same issue. I'll probably look into it more over the next week, but did you find a solution? If so, what worked for you?

**Reply by slickygreasefat** [reply]
I couldn't find a solution unfortunately. This shouldn't be so complex to install this. But for some reason it  is(especially with a program like Krita)..

**Reply by elmagio** [reply]
For what it's worth I found a solution that lets me launch the server successfully without this error, it turns out I was just lacking some system packages (intel-compute-runtime, oneapi-level-zero and some dependencies, may have other names on your distro), however image generation still fails with the server crashing with a SegFault. That might just be my GPU so maybe you'd have better luck.

**Reply by slickygreasefat** [reply]
could you send me the link to the system packages you downloaded (intel-compute-runtime, oneapi-level-zero and some dependencies) and where do I need to install these in? If that is true, this will be great and I wont have to pay AI programs every month to generate content.

**Reply by elmagio** [reply]
I don't have a link, they're packages for my Linux distro. You should check your Intel GPU drivers, I don't know how that works on Windows.
