### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by Skerol** [Acly/krita-ai-diffusion#116]
Got this error message when trying to launch for the first time.

>2023-11-24 21:25:15,846 ERROR Traceback (most recent call last):
  File "C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\main.py", line 72, in <module>
    import execution
  File "C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\execution.py", line 12, in <module>
    import nodes
  File "C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\comfy\diffusers_load.py", line 4, in <module>
    import comfy.sd
  File "C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\comfy\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\comfy\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\49157\AppData\Roaming\Python\Python310\site-packages\torch\cuda\__init__.py", line 674, in current_device
    _lazy_init()
  File "C:\Users\49157\AppData\Roaming\Python\Python310\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

How do I fix the torch installation inside the internal Krita python?

Thanks in advance for any help!

**Comment by Acly** [comment]
If you installed with CUDA selected this is unexpected, as it should have installed the correct torch version. The error message actually refers to your system Python though (C:\Users\49157\AppData\Roaming\Python\Python310), which is strange. The installer uses its own (in `...\ai_diffusion\.server\python`).

client.log should contain a line like this "INFO Using Python: Python 3.10.11," followed by the path, can you check?
or are you are using your own Python on purpose?

**Comment by Skerol** [comment]
Yep, there is that line: 
> 2023-11-24 20:44:58,865 INFO Using Python: Python 3.10.11, C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe

**Comment by Skerol** [comment]
Ah but it is followed by this: 

> 2023-11-24 20:45:01,426 INFO Looking in indexes: https://download.pytorch.org/whl/cu121
2023-11-24 20:45:01,428 INFO Requirement already satisfied: torch in c:\users\49157\appdata\roaming\python\python310\site-packages (2.0.1)
2023-11-24 20:45:01,428 INFO Requirement already satisfied: torchvision in c:\users\49157\appdata\roaming\python\python310\site-packages (0.15.2)
2023-11-24 20:45:01,428 INFO Requirement already satisfied: torchaudio in c:\users\49157\appdata\roaming\python\python310\site-packages (2.0.2)
2023-11-24 20:45:01,428 INFO Requirement already satisfied: filelock in c:\users\49157\appdata\roaming\python\python310\site-packages (from torch) (3.12.0)
2023-11-24 20:45:01,429 INFO Requirement already satisfied: typing-extensions in c:\users\49157\appdata\roaming\python\python310\site-packages (from torch) (4.5.0)
2023-11-24 20:45:01,429 INFO Requirement already satisfied: sympy in c:\users\49157\appdata\roaming\python\python310\site-packages (from torch) (1.12)
2023-11-24 20:45:01,429 INFO Requirement already satisfied: networkx in c:\users\49157\appdata\roaming\python\python310\site-packages (from torch) (3.1)
2023-11-24 20:45:01,429 INFO Requirement already satisfied: jinja2 in c:\users\49157\appdata\roaming\python\python310\site-packages (from torch) (3.1.2)
2023-11-24 20:45:01,429 INFO Requirement already satisfied: numpy in c:\users\49157\appdata\roaming\python\python310\site-packages (from torchvision) (1.24.3)

So apparently the installer wants to use my system python?

**Comment by Acly** [comment]
Hm, it has installed its own python and is trying to use it. But somehow ends up installing packages for the system python. What is the command that is executed for the log output you posted? Should be right above. Something like:
```
INFO Executing C:\...\ai_diffusion\.server\python\python.exe -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
```

**Comment by Skerol** [comment]
It's this:
> 023-11-24 20:45:00,824 INFO Executing C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

**Comment by Acly** [comment]
Maybe this is default Python behavior and not necessarily bad, but could produce a conflict.
Can you try to set `PYTHONNOUSERSITE` environment variable and then run the torch install command manually (same you just copied from the log)?

**Comment by Skerol** [comment]
It appears to download now. This will take a while on my internet connection, will report the results.

**Comment by Skerol** [comment]
So it was successfully installed inside the Krita python. I can confirm that by importing torch while running that python installation. But if I manually launch the main.py script it still tries to switch over to the system python:

> C:\Users\49157>C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\main.py
Traceback (most recent call last):
  File "C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\main.py", line 72, in <module>
    import execution
  File "C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\execution.py", line 12, in <module>
    import nodes
  File "C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\comfy\diffusers_load.py", line 4, in <module>
    import comfy.sd
  File "C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\comfy\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\49157\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\comfy\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\49157\AppData\Roaming\Python\Python310\site-packages\torch\cuda\__init__.py", line 674, in current_device
    _lazy_init()
  File "C:\Users\49157\AppData\Roaming\Python\Python310\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by Skerol** [comment]
Setting PYTHONNOUSERSITE again does cause it to launch pytorch correctly.

**Comment by Acly** [comment]
Did you launch Krita with the environment variable set? I though it would be passed on to the python process.

In any case I will add the option to both installer and launcher, but it would be nice to already confirm that it works.

**Comment by Skerol** [comment]
Yes, launching with the environment variable set as true also allows everything to work inside Krita. I think I'll probably continue with that for now. Thanks for your quick response!

**Comment by Acly** [comment]
With [release 1.8.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.8.1) it should also work without the environment variable
