### ISSUE TITLE
"Server execution error"

### ISSUE THREAD

**Issue by Sphynxcolt** [Acly/krita-ai-diffusion#16]
Hey, I encountered an issue with, apparently, "Server Execution error: Torch not compiled with CUDA enabled", although I unchecked the "Use CUDA" option and selected my CPU in the performance settings.
![image](https://github.com/Acly/krita-ai-diffusion/assets/56783893/9bc9e01e-0280-4f59-b09a-2cc652ec51e5)

It seems to generate something but then just crashes the generation and pops up this error message.

**Comment by Acly** [comment]
Does this only happen with Strength at 100% and an active selection? Please try without selection if you haven't already.

**Comment by Sphynxcolt** [comment]
It seems to work now, without anything selection.

**Comment by Acly** [comment]
Okay, it's probably because of an extension that is used for 100% + selection and requires CUDA. I will switch to a different one which doesn't have this problem.
