### ISSUE TITLE
CUDA error: no kernel image is available… Compile with `TORCH_USE_CUDA_DSA`

### ISSUE THREAD

**Issue by ghost** [Acly/krita-ai-diffusion#1828]
After updating from version 1.33 to 1.35 I started getting this error:

```
Error de ejecución del servidor: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

- System specs:
    - Ubuntu 22.04.5
    - Krita 5.2.3
    - Nvidia GTX 1060
    - Nvidia driver 570.133.07
    - CUDA 12.8
- The error persist if server installation is deleted and freshly installed with plugin v1.35.
- Issue also present with plugin v1.34, although I didn't test a fresh server installation for this version.
- Downgrading the plugin to v1.33 is a workaround, didn't have to reinstall the server.
- Running ComfyUI with the Custom server option, via docker with this specific image `mmartial/comfyui-nvidia-docker:ubuntu24_cuda12.8-latest` also works.

**Comment by Acly** [comment]
This error is usually related to driver / pytorch version / gpu model. So it's unusual to see it working with the same server installation for one plugin version (1.33) but not the other (1.35). 

It would be great if you could verify that by using the [Dump Workflow](https://docs.interstice.cloud/common-issues/#comfyui-workflow-export) option:
* save the workflow that works from version 1.33 
* save the workflow that fails from version 1.35
* you can run and compare them in ComfyUI directly, it should show same behavior
* ... or just attach them here

(if they are identical it must be related to the server install somehow after all)

**Comment by ghost** [comment]
The workflows resulted being identical aside from a prompt typo and the random seed. The test was a simple image generation on a 512x512 canvas on default settings.

My hunch is that Comfy, Torch or some dependency is being compiled against/looking for an earlier CUDA version; such was the case for the docker, whose default image targeted CUDA 12.6 and didn't work for me. Could it be that the case be similar for the server installed by the plugin?

[workflow_135.json](https://github.com/user-attachments/files/20808987/workflow_135.json)
[workflow_133.json](https://github.com/user-attachments/files/20808986/workflow_133.json)

**Comment by Acly** [comment]
Since version 1.34 the managed server uses Torch for CUDA 12.8 (previously was 12.4 I think), so that is very likely source for the issue. But reverting the plugin to 1.33 would not magically fix that, unless the server is explicitly reinstalled.

I'd install latest NVIDIA drivers just to make sure it's not that.

Also, _earlier_ CUDA versions are usually not a problem. If you have a driver that supports CUDA 12.8 it can also run prior versions.

**Comment by ghost** [comment]
When swapping between plugin versions, the button that starts the server changes to _“Upgrade”_, and there is a message to the left in coloured text saying that an _“Upgrade is required: v1.34.0 -> v1.33.0”_.  Is this process reinstalling the server? I swear that just reinstalling the v1.33 and clicking that button, does the trick.

Running `ubuntu-drivers list` on a terminal lists all available drivers for my system, I already am on the latest, v570.

**Comment by Acly** [comment]
Yes "Upgrade" (or in this case downgrade) reinstalls the relevant parts of the server. So it's probably Torch 2.7.0+cu128 which is not working for you. Either because they dropped support for GTX 1000-series or because you don't have CUDA 12.8

**Comment by ghost** [comment]
I must have CUDA 12.8, nvidia-smi shows:
```
~$  nvidia-smi
Thu Jun 19 12:26:25 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.133.07             Driver Version: 570.133.07     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
```

And they likely haven't dropped support for my GPU since I can use it fine with the docker image (just my conjecture, the container people could have very well done something extra). But my hypothesis is that CUDA 12.8 is just not yet the default, the default being CUDA 12.6, so the problem would persist until CUDA 12.8 becomes the default or the correct version is installed.

The table in this site https://pytorch.org/get-started/locally/ (official site I believe) allows you to select a configuration and gives you the installation command.

For CUDA 12.6 is just:
        `pip3 install torch torchvision torchaudio` 
While the one for CUDA 11.8/12.8, ROCm and CPU all are appended with the specific version (like the following command), which reinforces my belief in that the defaults are the issue.
        `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128`

Now, how would I go about testing this hypothesis of installing the corresponding Torch version for the managed server?
Unless the managed server is already using this version? =S

**Comment by Acly** [comment]
From brief glance I had the impression the Docker container you use has CUDA 12.8 support, but uses the CUDA 12.6 version of Torch. The managed server uses the CUDA 12.8 version of Torch.

While it may not be the default, the torch+cu128 is also supposed to be stable, and that it's not the default is probably more related to many not having up-to-date drivers.

But to test the managed server with torch+cu126 you go to the folder where it's installed and do:
```
source venv/bin/activate
uv pip install -U torch torchvision torchaudio
```

**Comment by ghost** [comment]
You are correct, and that worked!

Had to `cd` into `ai_diffusion/server/ComfyUI` to then use `../uv/uv pip whatever`, and had to uninstall the packages first because it refused to just downgrade them. But after reinstalling them, it worked again. This is how the relevant packages looked originally with the server as it comes with plugin v1.35:

```
~/.local/share/krita/ai_diffusion/server/ComfyUI$ ../uv/uv  pip list | grep "torch"
Using Python 3.12.9 environment at: /home/carmeline/.local/share/krita/ai_diffusion/server/venv
torch                      2.7.1+cu128
torchaudio                 2.7.1+cu128
torchsde                   0.2.6
torchvision                0.22.1+cu128
```

And this is how they look now after downgrading them:
```
torch                      2.7.1
torchaudio                 2.7.1
torchsde                   0.2.6
torchvision                0.22.1
```

So, Torch 2.7.1+cu128 indeed dropped support for my GPU, rare for a minor update to break stuff, but it happens. Anyway, now it works again without downgrading the whole managed server and plugin.

But found a new problem, when trying to use the copy face feature it gave me this error:
`RuntimeError: Expected query, key, and value to have the same dtype, but got query.dtype: float key.dtype: c10::Half and value.dtype: c10::Half instead.`

After much investigation, turns out that `ComfyUI/comfy/ldm/modules/attention.py` has a function `attention_pytorch` (line 431) which requires `query`, `key`, and `value` to be of the same type, but `q` is float32 (`dtype: float`) while `k` and `v` are float16 (`dtype: c10::Half`), so had to modify this function, homogenizing dtypes, for the face transfer to work again. Did so by prepending the following snippet just before `if SDP_BATCH_LIMIT >= b:`  so it looks like this:

```
# Check if k and v types don't match q's data type , if so, change their type.
if k.dtype != q.dtype:
        k = k.to(q.dtype)
if v.dtype != q.dtype:
        v = v.to(q.dtype)
# End of dtype snippet

 if SDP_BATCH_LIMIT >= b:
        out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
```

There is a one-year-old pull request to fix this last issue at ComfyUI's Github repo at https://github.com/comfyanonymous/ComfyUI/pull/3637 with a more compressive approach, but is still unmerged. My guess is that this bug only affects Pascal cards, because from Turing and onward, GPUs support half precision natively.

And that's it, I wanted to leave this here because is somewhat related even when is not caused by the plugin, just in case someone else hits the same rock. Ooof, I learned a lot today, and for now it works again! Sadly, I think that there ain't much that you could do about these two problems, software will keep progressing, leaving behind the oldest hardware.

Thank you for the help and super timely responses, but mostly, I wanted to thank you for the awesome plugin that you crafted and then kindly gave away freely to everyone. For me, it has been an unexpectedly fun tool to use because it integrates naturally in the creative process (unlike Adobe's AI lol), I think that you nailed it.

Thank you very much!

**Comment by Dahvikiin** [comment]
using pip install or -U `torch torchvision torchaudio` without the `--index-url https://download.pytorch.org/whl/cu[version]` uses the torch **CPU** version from pypi.

Also the fp16 support for 1600-series is somewhat... questionable. yes. the RTX and GTX are both Turing. Even CUDA12.9 still supports them. but, BUT the HW is different, the `TU10X` has tensor cores and the `TU11X` doesn't, which makes the TU10X (like the RTX 2000 series) superior. and since they are both sm75, there is no direct way to identify them. that's why GTX 1600 users usually use fp32 (--fp32 and/or --cast args), because fp16 is slower and usually fails with NaN or black squares.

**Comment by Acly** [comment]
> using pip install or -U torch torchvision torchaudio without the --index-url https://download.pytorch.org/whl/cu[version] uses the torch CPU version from pypi.

afaik that's true for Windows, but not Linux?

Good point on fp16 vs fp32, sounds like `--force-fp32` might be the easier and better way to resolve this.
