### ISSUE TITLE
Flux.1 dev FP8 Model Causes torch.OutOfMemoryError on RTX 4060 Ti 16GB

### ISSUE THREAD

**Issue by dexterhuh** [Acly/krita-ai-diffusion#1911]
Hello, ​can someone please help me debug this Flux model OOM issue?​​ I'm hoping for troubleshooting guidance or temporary workarounds to get this working. Below is all my faced issue information:

Flux.1 dev FP8 Model Causes torch.OutOfMemoryError on RTX 4060 Ti 16GB

**Setup Configuration**
​Guide Followed: Option 1 of Flux Support #1176 
> Option 1: Full Checkpoint
> The easiest way is to download a full checkpoint which includes everything in one package. Choose any of the following models:
> 
> [Flux.1 dev - FP8](https://huggingface.co/Comfy-Org/flux1-dev/resolve/main/flux1-dev-fp8.safetensors) → /models/checkpoints
> [Flux.1 schnell - FP8](https://huggingface.co/Comfy-Org/flux1-schnell/resolve/main/flux1-schnell-fp8.safetensors) → /models/checkpoints
> The models must be placed into the /models/checkpoints folder. Then you will be able to choose them from the Checkpoint list in the Style settings.
> 
> 16 GB VRAM recommended, but it will work with less.

1. Model Used:
```
flux1-dev-fp8.safetensors from Comfy-Org/flux1-dev
Location: F:\ComfyUI_windows_portable\ComfyUI\models\checkpoints
```
​2. Hardware:
```
GPU: ​NVIDIA GeForce RTX 4060 Ti​ (16GB VRAM)
VRAM: 16GB (per torch.cuda.mem_get_info())
System RAM: 32GB
```
​3. Software:
```
ComfyUI v0.3.10 (Portable Windows Build)
Torch 2.5.1+cu124
```
**Repoduce steps**
1. Downloaded flux1-dev-fp8.safetensors as per guide
2. Placed in correct checkpoints directory
3. Launched ComfyUI with:
```
.\python_embeded\python.exe -s ComfyUI\main.py ^
  --windows-standalone-build ^
  --dont-upcast-attention ^
  --normalvram
```
4. Created 512x512 canvas in Krita
5. Selected "Flux" model in Diffusion plugin
6. Entered sample prompt → Clicked "Generate"
**Excepted Result:** 
`The model should run on 16GB VRAM as the guild Flux Support #1176 said 16 GB VRAM recommended, but it will work with less.`
**Actual Result:**
`torch.OutOfMemoryError: Allocation on device`
**Full log:**
```
F:\ComfyUI_windows_portable>.\python_embeded\python.exe -c "import torch; print(f'Available VRAM: {torch.cuda.mem_get_info()[1]/1024**3:.2f}GB')"   & .\python_embeded\python.exe -s ComfyUI\main.py   --windows-standalone-build   --dont-upcast-attention   --normalvram
Available VRAM: 16.00GB
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-07-29 15:21:05.192688
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: F:\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: F:\ComfyUI_windows_portable\ComfyUI
** Log path: F:\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   3.1 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16380 MB, total RAM 32655 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using pytorch attention
[Prompt Server] web root: F:\ComfyUI_windows_portable\ComfyUI\web
### Loading: ComfyUI-Manager (V2.55.5)
### ComfyUI Version: v0.3.10 | Released on '2024-12-26'
[comfyui_controlnet_aux] | INFO -> Using ckpts path: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")

Import times for custom nodes:
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.3 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tooling-nodes
   0.4 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
FETCH DATA from: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
got prompt
model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
model_type FLUX
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 568, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 826, in load_checkpoint_guess_config
    out = load_state_dict_guess_config(sd, output_vae, output_clip, output_clipvision, embedding_directory, output_model, model_options, te_model_options=te_model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 880, in load_state_dict_guess_config
    clip = CLIP(clip_target, embedding_directory=embedding_directory, tokenizer_data=clip_sd, parameters=parameters, model_options=te_model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 96, in __init__
    self.cond_stage_model = clip(**(params))
                            ^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\text_encoders\flux.py", line 71, in __init__
    super().__init__(dtype_t5=dtype_t5, device=device, dtype=dtype, model_options=model_options)
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\text_encoders\flux.py", line 40, in __init__
    self.t5xxl = comfy.text_encoders.sd3_clip.T5XXLModel(device=device, dtype=dtype_t5, model_options=model_options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\text_encoders\sd3_clip.py", line 18, in __init__
    super().__init__(device=device, layer=layer, layer_idx=layer_idx, textmodel_json_config=textmodel_json_config, dtype=dtype, special_tokens={"end": 1, "pad": 0}, model_class=comfy.text_encoders.t5.T5, enable_attention_masks=attention_mask, return_attention_masks=attention_mask, model_options=model_options)
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\sd1_clip.py", line 114, in __init__
    self.transformer = model_class(config, dtype, device, self.operations)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\text_encoders\t5.py", line 231, in __init__
    self.encoder = T5Stack(self.num_layers, model_dim, model_dim, config_dict["d_ff"], config_dict["dense_act_fn"], config_dict["is_gated_act"], config_dict["num_heads"], config_dict["model_type"] != "umt5", dtype, device, operations)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\text_encoders\t5.py", line 197, in __init__
    [T5Block(model_dim, inner_dim, ff_dim, ff_activation, gated_act, num_heads, relative_attention_bias=((not relative_attention) or (i == 0)), dtype=dtype, device=device, operations=operations) for i in range(num_layers)]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\text_encoders\t5.py", line 184, in __init__
    self.layer.append(T5LayerSelfAttention(model_dim, inner_dim, ff_dim, num_heads, relative_attention_bias, dtype, device, operations))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\text_encoders\t5.py", line 170, in __init__
    self.SelfAttention = T5Attention(model_dim, inner_dim, num_heads, relative_attention_bias, dtype, device, operations)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\text_encoders\t5.py", line 77, in __init__
    self.k = operations.Linear(model_dim, inner_dim, bias=False, dtype=dtype, device=device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\linear.py", line 106, in __init__
    torch.empty((out_features, in_features), **factory_kwargs)
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.
Prompt executed in 16.60 seconds
```

**Comment by Acly** [comment]
Try without these: --dont-upcast-attention --normalvram
Adding --fast could make sense

Does it work in ComfyUI directly? If not you are more likely to get help there.

**Comment by dexterhuh** [comment]
> Try without these: --dont-upcast-attention --normalvram Adding --fast could make sense
> 
> Does it work in ComfyUI directly? If not, you are more likely to get help there.

You are right! I think the issue was related to ComfyUI or its dependencies. ​The issue was resolved after I upgraded ComfyUI and updated CUDA from 12.4 to 12.8.​

**​Edit:​​ The problem wasn’t that ComfyUI wasn’t up to date—I eventually found the exact cause. It was due to insufficient RAM. I have 32GB of RAM, and if I don’t have too many apps running in the background, I don’t encounter this issue. However, if background apps consume too much RAM, the problem arises.

After upgrading to 48GB of RAM, I’ve never faced this issue again. I suspect that when loading this model into VRAM, the program first extracts it to RAM, which requires a significant amount of available memory. If there isn’t enough free RAM during this process, you’ll run into an out-of-memory (OOM) error.**
