### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by Lord-Vlad** [Acly/krita-ai-diffusion#457]
Error message:
```
  File "/home/user/.local/share/krita/ai_diffusion/server/ComfyUI/main.py", line 76, in <module>
    import execution
  File "/home/user/.local/share/krita/ai_diffusion/server/ComfyUI/execution.py", line 11, in <module>
    import nodes
  File "/home/user/.local/share/krita/ai_diffusion/server/ComfyUI/nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "/home/user/.local/share/krita/ai_diffusion/server/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/home/user/.local/share/krita/ai_diffusion/server/ComfyUI/comfy/sd.py", line 3, in <module>
    from comfy import model_management
  File "/home/user/.local/share/krita/ai_diffusion/server/ComfyUI/comfy/model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/home/user/.local/share/krita/ai_diffusion/server/ComfyUI/comfy/model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/home/user/.local/share/krita/ai_diffusion/server/venv/lib64/python3.10/site-packages/torch/cuda/__init__.py", line 787, in current_device
    _lazy_init()
  File "/home/user/.local/share/krita/ai_diffusion/server/venv/lib64/python3.10/site-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 803: system has unsupported display driver / cuda driver combination
```

I strongly believe this is because I just updated my NVIDIA drivers, so nothing wrong with the plugin. But I'd like to know if I can do anything besides downgrading the driver.

**Comment by Acly** [comment]
You might find something by searching for the error in combination with "torch". It's unlikely the driver is incompatible, I suspect the install is broken somehow.

**Comment by Lord-Vlad** [comment]
Ok, thank you. I will try that.

**Comment by Lord-Vlad** [comment]
It turns out my cuda version wasn't updated with the latest driver version.
